title:  "An Atonal Life"
tagline:  a blog by Kenny Xu
author:
  name: "Kenny Xu"
  twitter:  XuKenny

menu:
- {name: 'Home', url: '../'}
- {name: 'About', url: 'about.html'}
- {name: 'Writing', url: 'writing.html'}
- {name: 'Subscribe', url: 'subscribe.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/xukenny'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/kennyx/'}
- {icon: 'envelope', link: 'mailto:kxu2@nd.edu'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
