title:  "Life Through Song"
tagline:  a blog about creativity and happiness
author:
  name: "Kenny Xu"
  twitter:  kennythexu

menu:
- {name: 'Writing', url: 'writing.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/xukenny'}
- {icon: 'instagram', link: 'https://instagram.com/kennythexu'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/kennyx/'}
- {icon: 'envelope', link: 'mailto:kxu2@nd.edu'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
